#!/bin/sh
python3 -m venv venv
. venv/bin/activate
pip install Flask
pip install Flask-SQLAlchemy
pip install flask-bcrypt
pip install flask-wtf
pip install flask-login
pip install flask-bootstrap
pip install flask-nav
pip install flask-socketio
pip install wheel
pip install greenlet
pip install gevent
pip install gevent-websocket
./run
